sudo: false
language: node_js
install:
- npm install
- npm install grunt-cli bower -g
- bower install
- openssl aes-256-cbc -K $encrypted_a298b6b30e99_key -iv $encrypted_a298b6b30e99_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
after_success:
- grunt stage:web
before_deploy:
- grunt deploy:web
- grunt clean
#- grunt deploy:packaged
#- grunt clean
- grunt travis
deploy:
  provider: releases
  api_key:
    secure: WD1D5Msv6LDpmEebU+OkyIh+hhLTeOXQtK7DcdVIOnd781iPJYKyUeCkHcf6B8hC9GgfRcXm4DE5ThUGLgO8vwXEZ1Ayu3DtE10ezcQDXfh3gFZVplXrQALg03JpMhgPlTJud6sRzb/rPmXPLCn/R6vsI6o5cGZvT5NNERgjqb0=
  file: mines.zip
  on:
    tags: true
